// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVOsv_wkCT8zzknpDJ1iZE5nV_i49TH0',
    appId: '1:754562508062:web:7955285d050b8a783fd50f',
    messagingSenderId: '754562508062',
    projectId: 'nodeflutter-c525b',
    authDomain: 'nodeflutter-c525b.firebaseapp.com',
    storageBucket: 'nodeflutter-c525b.appspot.com',
    measurementId: 'G-MTTXVRG9SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcqWEiGR24QB76mH5hOGY8mNuWOvWF6A',
    appId: '1:754562508062:android:7e33dee415c49dd03fd50f',
    messagingSenderId: '754562508062',
    projectId: 'nodeflutter-c525b',
    storageBucket: 'nodeflutter-c525b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp1otYgoUIJefMstV8bXO_l0YasuCrQSE',
    appId: '1:754562508062:ios:138bbcc28be0b9873fd50f',
    messagingSenderId: '754562508062',
    projectId: 'nodeflutter-c525b',
    storageBucket: 'nodeflutter-c525b.appspot.com',
    iosBundleId: 'com.example.nodeflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp1otYgoUIJefMstV8bXO_l0YasuCrQSE',
    appId: '1:754562508062:ios:85ad1f6e7cc7725e3fd50f',
    messagingSenderId: '754562508062',
    projectId: 'nodeflutter-c525b',
    storageBucket: 'nodeflutter-c525b.appspot.com',
    iosBundleId: 'com.example.nodeflutter.RunnerTests',
  );
}
